[package]
name = "my-game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.2", features = [ "wav" ] }
bevy_ecs_ldtk = "0.10.0"
bevy_rapier2d = "0.27.0"
leafwing-input-manager = "0.15.1"